from pathlib import Path

import pandas as pd

app_dir = Path(__file__).parent
chicago_df = pd.read_csv(app_dir / "chicago_out.csv")
la_df = pd.read_csv(app_dir / "la_inspections.csv")
nyc_df = pd.read_csv(app_dir / "nyc-out.csv")

chicago_facility_types = [
    "After School Program",
"Assisted Living",
"Assisted Living Senior Care",
"Bakery",
"Banquet",
"Bar",
"Bar/Grill",
"Butcher",
"Cafeteria",
"Candy",
"Candy/Gelato",
"Catering",
"Charity Aid Kitchen",
"Children's Services Facility",
"Church",
"City of Chicago College",
"Coffee",
"Cold Storage Facility",
"College",
"Commissary",
"Convenience",
"Cooking Instruction",
"Day Care",
"Deli",
"Dollar Store",
"Donut Shop",
"Drug Store",
"Employee Kitchen",
"Farmers Market",
"Fish Market",
"Fitness Center",
"Frozen Dessert",
"Gas Station",
"General Store",
"Golden Diner",
"Grocery",
"Health Center",
"Hooka",
"Hospital",
"Hot Dog",
"Hotel",
"Incubator",
"Juice Bar",
"Kids Cafe",
"Kiosk",
"Limited Business",
"Liquor",
"Long Term Care",
"Main Kitchen",
"Meat Packing",
"Mobile Food",
"Movie Theater",
"Newsstand",
"Night Club",
"Nonprofit",
"Nursing Home",
"Nutrition Store",
"Other",
"Pantry",
"Peddler",
"Pharmacy",
"Pool",
"Prepackaged",
"Private School",
"Produce Stand",
"Protein Shake Bar",
"Public School",
"Religious",
"Restaurant",
"Restaurant/Grocery",
"Restaurant/Liquor",
"Retail",
"Riverwalk",
"Rooftop",
"Room Service",
"School",
"Shared Kitchen",
"Shelter",
"Slaughterhouse",
"Snack Shop",
"Social Club",
"Soup Kitchen",
"Special Event",
"Store",
"Summer Feeding",
"Tavern",
"Teaching School",
"Theater",
"Unlicensed",
"Waterlemon House",
"Weight Loss Program",
"Wholesale",
"Bakery/Deli",
"Bakery/Restaurant",
"Before And After School Program",
"Boys And Girls Club",
"Drug Treatment Facility",
"Food Pantry",
"Golf Course",
"Meat Market",
"Popcorn",
"Rehab Center",
"Senior Day Care",
"Smokehouse",
"Stadium",
"Supportive Living",
"Tent Restaurant",
"Video Store",
"Warehouse",
"Wine",
"Alternative School",
"Beverage/Silverware Warehouse",
"blockbuster video",
"Cafe",
"Charter School",
"Chicago Park District",
"Chinese Herbs",
"Herbal",
"Hostel",
"Illegal Vendor",
"Laundromat",
"Music Venue",
"Nail Shop",
"Tea",
"University CAFETERIA",
"Adult Family Care Center",
"Bakery/Grocery",
"Book Store",
"Car Wash",
"Day Spa",
"Lounge",
"Packaged Food Distribution",
"REGULATED BUSINESS",
"Repackaging plant",
"Unused Storage",
"15 months to 5 years old",
"Art Gallery With Wine And Beer",
"Bowling Lanes",
"Brewery",
"Butcher Shop",
"Day Care Above 2 Years",
"Health Care Store",
"Northerly Island",
"Push Carts",
"Truck",
"Vfw Hall",
"Cell Phone Store",
"Custom Poultry Slaughter",
"Distribution Center",
"Massage",
"Mfd Truck",
"Service Bar",
"Urban Farm",
"Airport Lounge",
"Art Gallery",
"Dining Hall",
"Distributor",
"Kitchen Demo",
"Museum",
"Smoothie Bar",
"Spa",
"Vending Machine",
"Animal Shelter Cafe Permit",
"Event Center",
"French Market Space",
"Furniture Store",
"Gift Shop",
"High School",
"ADULT DAYCARE",
"Clothing Store",
"Internet Cafe",
"Shakes/Teas",
"Sushi",
"Youth Housing",
"Art Center",
"CHARTER",
"Greenhouse",
"Health Care",
"Health Food Store",
"Health Foods",
"Frozen Desserts",
"Pop-Up Establishment",
"Private",
"Shared Kitchen",
"Archdiocese",
"Distillery",
"Flea Market",
"Food Booth",
"Hair Salon",
"Storage",
"Adult Day Service",
"THC INFUSED BAKERY",
"University",
"Entertainment",
]

la_facility_types = [
    "FOOD MKT RETAIL (2,000+ SF) HIGH RISK",
    "FOOD MKT RETAIL (2,000+ SF) LOW RISK",
    "FOOD MKT RETAIL (2,000+ SF) MODERATE RISK",
    "FOOD MKT RETAIL (25-1,999 SF) HIGH RISK",
    "FOOD MKT RETAIL (25-1,999 SF) LOW RISK",
    "FOOD MKT RETAIL (25-1,999 SF) MODERATE RISK",
    "RESTAURANT (0-30) SEATS HIGH RISK",
    "RESTAURANT (0-30) SEATS LOW RISK",
    "RESTAURANT (0-30) SEATS MODERATE RISK",
    "RESTAURANT (151 + ) SEATS HIGH RISK",
    "RESTAURANT (151 + ) SEATS LOW RISK",
    "RESTAURANT (151 + ) SEATS MODERATE RISK",
    "RESTAURANT (31-60) SEATS HIGH RISK",
    "RESTAURANT (31-60) SEATS LOW RISK",
    "RESTAURANT (31-60) SEATS MODERATE RISK",
    "RESTAURANT (61-150) SEATS HIGH RISK",
    "RESTAURANT (61-150) SEATS LOW RISK",
    "RESTAURANT (61-150) SEATS MODERATE RISK",
    "CATERER (0-999 SQ. FT.)",
    "FOOD MARKET WHOLESALE",
    "FOOD MKT RETAIL (1-1,999 SF) HIGH RISK",
    "FOOD MKT RETAIL (1-1,999 SF) LOW RISK",
    "FOOD MKT RETAIL (1-1,999 SF) MODERATE RISK",
    "FOOD PROCESSING WHOLESALE (2,000-5,999 SF)",
    "LIC HTH CARE FOOD FAC (2000-3999 SF)HIGH RISK",
    "LIC HTH CARE FOOD FAC (4000-9999 SF)HIGH RISK",
    "SENIOR FEEDING SITE",
    "WHOLESALE FOOD COMPLEX",
    "PRIVATE SCHOOL CAFETERIA",
    "FOOD WAREHOUSE (1-4,999) SQ. FT.",
]

nyc_facility_types = [
    "Other",
"American",
"Mediterranean",
"Vegan",
"Spanish",
"Sandwiches/Salads/Mixed Buffet",
"Latin American",
"Hotdogs",
"Caribbean",
"Bottled Beverages",
"Japanese",
"Korean",
"Mexican",
"Coffee/Tea",
"Hamburgers",
"Italian",
"Middle Eastern",
"German",
"Soups/Salads/Sandwiches",
"Jewish/Kosher",
"Pizza",
"Chinese",
"French",
"Bagels/Pretzels",
"Nuts/Confectionary",
"Juice, Smoothies, Fruit Salads",
"Seafood",
"Russian",
"Frozen Desserts",
"African",
"Ethiopian",
"Sandwiches",
"Eastern European",
"Greek",
"Peruvian",
"Asian/Asian Fusion",
"Donuts",
"Tapas",
"Fruits/Vegetables",
"Polish",
"Tex-Mex",
"Vegetarian",
"Brazilian",
"Indian",
"Barbecue",
"Hotdogs/Pretzels",
"Bakery Products/Desserts",
"Steakhouse",
"Southeast Asian",
"Turkish",
"Indonesian",
"Australian",
"Salads",
"Chicken",
"Irish",
"Fusion",
"Hawaiian",
"Creole",
"Soul Food",
"Cajun",
"Thai",
"Pakistani",
"Bangladeshi",
"Egyptian",
"Iranian",
"Lebanese",
"Filipino",
"Not Listed/Not Applicable",
"New American",
"English",
"Afghan",
"Chilean",
"Moroccan",
"Chinese/Japanese",
"New French",
"Soups",
"Portuguese",
"Continental",
"Californian",
"Pancakes/Waffles",
"Chinese/Cuban",
"Creole/Cajun",
"Basque",
"Scandinavian",
"Haute Cuisine",
"Czech",
"Armenian",
"Chimichurri",
"Southwestern",
]